spring.application.name=autoServe-vsm

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/autoserve_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=YourVeryLongSecretKeyForAutoServeProject123456789
jwt.expiration=86400000

razorpay.key.id=rzp_test_TM19sxJsX0L3ij

razorpay.key.secret=t4KcFbB4eMNPO7x5i8u1nARF

# ==========================
# MAIL CONFIGURATION
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=piratekingemperorluffy@gmail.com
spring.mail.password=mfxq iiws hiqe ohch

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

debug=true